/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hdiff_Hdiff */

#ifndef _Included_hdiff_Hdiff
#define _Included_hdiff_Hdiff
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hdiff_Hdiff
 * Method:    hdiff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_hdiff_Hdiff_hdiff
(JNIEnv *env, jobject thiz, jstring oldFilePath, jstring diffFilePath,
                                        jstring newFilePath);

#ifdef __cplusplus
}
#endif
#endif
