/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hpatch_Hpatch */

#ifndef _Included_hpatch_Hpatch
#define _Included_hpatch_Hpatch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hpatch_Hpatch
 * Method:    hpatch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_hpatch_Hpatch_hpatch
    (JNIEnv *env, jobject thiz, jstring oldFilePath, jstring diffFilePath,
                                        jstring newFilePath);

#ifdef __cplusplus
}
#endif
#endif
