/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hello_HelloJNI */

#ifndef _Included_hello_HelloJNI
#define _Included_hello_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hello_HelloJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hello_HelloJNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
